// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuXxSMkGRGL7UFdIXTamMQmJYNoQebv-U',
    appId: '1:765424169022:web:4a7d56284ec8b6c3b4216f',
    messagingSenderId: '765424169022',
    projectId: 'itskool-526ed',
    authDomain: 'itskool-526ed.firebaseapp.com',
    storageBucket: 'itskool-526ed.firebasestorage.app',
    measurementId: 'G-3104TJVH5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV08pW-JszjPctget2pzd7GVI5pfX85Uc',
    appId: '1:765424169022:android:8396b819e61e86c2b4216f',
    messagingSenderId: '765424169022',
    projectId: 'itskool-526ed',
    storageBucket: 'itskool-526ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRt29__qKnj5Pw2w8-QLu5bj593-tJ9_I',
    appId: '1:765424169022:ios:7c79e4e4316dbc17b4216f',
    messagingSenderId: '765424169022',
    projectId: 'itskool-526ed',
    storageBucket: 'itskool-526ed.firebasestorage.app',
    iosBundleId: 'com.example.itskoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRt29__qKnj5Pw2w8-QLu5bj593-tJ9_I',
    appId: '1:765424169022:ios:7c79e4e4316dbc17b4216f',
    messagingSenderId: '765424169022',
    projectId: 'itskool-526ed',
    storageBucket: 'itskool-526ed.firebasestorage.app',
    iosBundleId: 'com.example.itskoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuXxSMkGRGL7UFdIXTamMQmJYNoQebv-U',
    appId: '1:765424169022:web:4a7d56284ec8b6c3b4216f',
    messagingSenderId: '765424169022',
    projectId: 'itskool-526ed',
    authDomain: 'itskool-526ed.firebaseapp.com',
    storageBucket: 'itskool-526ed.firebasestorage.app',
    measurementId: 'G-3104TJVH5T',
  );

}